In [116]:
import numpy as np
from scipy.linalg import expm
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter

In [117]:
def tensor(A, B):
    m = len(A)*len(B)
    n = len(A[0])*len(B[0])

    prod = []

    for i in range(m):
        prod.append([])
        for j in range(n):
            ax = int(i / len(B))
            ay = int(j / len(B[0]))
            bx = int(i % len(B))
            by = int(j % len(B[0]))
            prod[i].append(A[ax][ay]*B[bx][by])

    return np.array(prod)

def tensor_list(ops):
    prod = ops[-1]
    for i in range(len(ops)-2, -1, -1):
        prod = tensor(ops[i], prod)
    return np.array(prod)

def pauli(pos, dir, N):
    factors = [[[1, 0], [0, 1]]]*N
    if dir == 'x':
        factors[pos] = [[0, 1], [1, 0]]
    elif dir == 'y':
        factors[pos] = [[0, -1j], [1j, 0]]
    elif dir == 'z':
        factors[pos] = [[1, 0], [0, -1]]

    return tensor_list(factors)

def on_site_detuning(pos, N):
    sum = 0
    for j in range(N):
        if np.abs(pos - j) == 1:
            sum += V_nn
        elif np.abs(pos - j) == 2:
            sum += V_nnn

    return -0.5 * sum

def interaction_strength(pos1, pos2):
    if np.abs(pos1 - pos2) == 1:
        return V_nn
    if np.abs(pos1 - pos2) == 2:
        return V_nnn
    else:
        return 0

In [118]:
N = 3
state_v = tensor_list([[[1], [0]], [[1], [0]], [[1], [0]]])
f = np.reshape(state_v, (2, 2**(N-1)))
gamma1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
print(f)
print(gamma1, lambda1, V1)

# rewrite in terms of local basis of i2
tau1 = np.hsplit(V1, 2)
print(tau1[1])
svds = [np.linalg.svd(tau) for tau in tau1]
gamma2 = [svds[0][0], svds[1][0]]
lambda2 = [svds[0][1], svds[1][1]]
V2 = [svds[0][2], svds[1][2]]

svds[0]
svds[1]


[[1 0 0 0]
 [0 0 0 0]]
[[1. 0.]
 [0. 1.]] [1. 0.] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0.]
 [0. 0.]]


(array([[1., 0.],
        [0., 1.]]),
 array([0., 0.]),
 array([[1., 0.],
        [0., 1.]]))

In [119]:
N = 4
state_v = tensor_list([[[1], [0]]] * N)
f = np.reshape(state_v, (2, 2**(N-1)))
A1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
# diag1 = np.zeros((V1.shape[0], V1.shape[0]), dtype=np.int32)
# lambda1 = np.diag(lambda1)
# diag1[:lambda1.shape[0], :lambda1.shape[1]] = lambda1
# SV = diag1 @ V1
# U, lambda2, V2 = np.linalg.svd(np.reshape(diag1 @ V1, (4, 2)), full_matrices=True)
U, lambda2, V2 = np.linalg.svd(np.reshape(np.diag(lambda1) @ V1, (4, 4)))
# print(U, lambda2, V2)
A2 = np.reshape(U, (2, 2, 4))
print(A2)
U, lambda3, V3 = np.linalg.svd(np.reshape(np.diag(lambda2) @ V2, (8, 2)))
A3 = np.reshape(U, (2, 2, 16))
print(A3)

U, lambda4, V4 = np.linalg.svd(np.reshape(np.diag(lambda3) @ V3, (4, 4)))
A4 = np.reshape(U, (2, 2, 4))

U, lambda5, V5 = np.linalg.svd(np.diag(lambda4) @ V4)
A5 = 

SyntaxError: invalid syntax (2763040447.py, line 22)

In [ ]:
N = 3
state_v = tensor_list([[[0], [1]]] * N)
f = np.reshape(state_v, (2, 2**(N-1)))
A1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
for i in range(1, N):
    U, lambda2, V2 = np.linalg.svd(np.reshape(np.diag(lambda1) @ V1, (2**c, 2**())))

In [1]:
def contract(mps, N):
    state_vec = []
    for i in range(2**N):
        ind = [int(bit) for bit in format(i, '0{}b'.format(N))]
        prod = [[row[ind[-1]]] for row in mps[-1]]
        for j in range(len(mps)-2, -1, -1):
            tensors = mps[j]
            prod = tensors[1] @ prod
            prod = tensors[0][ind[j]] @ prod
        if i == 3:
            print(ind)
            print(prod[0])
        state_vec.append(prod[0])
    return state_vec

In [194]:
tensor_list([[[1], [0]], [[0], [1]], [[1], [0]]])

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [363]:
N = 4
state_v = tensor_list([[[1], [0]]]*N)
f = np.reshape(state_v, (2, 2**(N-1)))
gamma1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)

# reshape V1
# V1 = np.reshape(V1, (2**2, 2**(N-2)))
# gamma2, lambda2, V2 = np.linalg.svd(V1, full_matrices=False)
# print("G2")
# print(gamma2, lambda2, V2)
# gamma2 = np.reshape(gamma2, (2, 2, 4))
# V2 = np.reshape(V2, (2**3, 2**(N-3)))
# gamma3, lambda3, V3 = np.linalg.svd(V2, full_matrices=False)
# gamma3 = np.reshape(gamma3, (2, 4, 2))
# gamma4, lambda4, V4 = np.linalg.svd(V3, full_matrices=False)
# print(gamma1)
# print(lambda1)
# print(gamma2)
# print(lambda2)
# print(gamma3)
# print(lambda3)
# print(gamma4)
# print("Yep")
# print("Gamma4")
# print(gamma4)

V1 = np.reshape(V1, (2, 2, 2**(N-2)))
gamma21, lambda21, V21 = np.linalg.svd(V1[0], full_matrices=False)
gamma22, lambda22, V22 = np.linalg.svd(V1[1], full_matrices=False)
print(gamma21, lambda21, V21)
gamma2 = [gamma21, gamma22]
V2 = [V21, V22]
V2 = np.reshape(V2, (2, 2**2, 2**(N-3)))
gamma31, lambda31, V31 = np.linalg.svd(V2[0], full_matrices=False)
gamma32, lambda32, V32 = np.linalg.svd(V2[1], full_matrices=False)
gamma3 = [gamma31, gamma32]
V3 = [V31, V32]
# V3 = np.reshape(V3, (2, 2, 2**(N-2)))
gamma41, lambda41, V41 = np.linalg.svd(V3[0], full_matrices=False)
gamma42, lambda42, V42 = np.linalg.svd(V3[1], full_matrices=False)
gamma4 = gamma41

lambda1 = np.diag(lambda1)
lambda2 = np.diag(lambda21)
lambda3 = np.diag(lambda31)
lambda4 = np.diag(lambda41)

print(gamma1)
print(lambda1)
print(gamma2)
print(lambda2)
print(gamma3)
print(lambda3)
print(gamma4)

mps = [[gamma1, lambda1], [gamma2, lambda2], [gamma3, lambda3], gamma4]

contract(mps, 4)


[[1. 0.]
 [0. 1.]] [1. 0.] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 0.]]
[array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
[[1. 0.]
 [0. 0.]]
[array([[ 1.,  0.],
       [ 0.,  0.],
       [ 0., -1.],
       [ 0.,  0.]]), array([[ 0., -1.],
       [ 0.,  0.],
       [ 1.,  0.],
       [ 0.,  0.]])]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [2]:
import numpy as np
# state_v = [0, 1/np.sqrt(3), 1/np.sqrt(3), 0, 1/np.sqrt(3), 0, 0, 0]
# state_v = tensor_list([[[1], [0]]]*N)
# state_v = tensor_list([[[1], [0]], [[1], [0]], [[0], [1]]])
def mps_3_split():
    N = 3
    state_v = [1,0,0,0,0,0,0,0]
    f = np.reshape(state_v, (2, 2**(N-1)))
    gamma1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
    print(V1)
    # reshape V1
    V1 = np.reshape(V1, (2, 2, 2**(N-2)))
    print(V1)
    gamma21, lambda21, V21 = np.linalg.svd(V1[0], full_matrices=False)
    gamma22, lambda22, V22 = np.linalg.svd(V1[1], full_matrices=False)
    gamma2 = [gamma21, gamma22]
    gamma31, lambda31, V31 = np.linalg.svd(V21, full_matrices=False)
    gamma32, lambda32, V32 = np.linalg.svd(V22, full_matrices=False)
    gamma3 = gamma31

    lambda1 = np.diag(lambda1)
    lambda2 = np.diag(lambda21)
    lambda3 = np.diag(lambda31)

    print(gamma1)
    print(lambda1)
    print(gamma2)
    print(lambda2)
    print(gamma3)

    mps = [[gamma1, lambda1], [gamma2, lambda2], gamma3]

    return contract(mps, N)
mps_3_split()


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[[1. 0.]
  [0. 0.]]

 [[0. 1.]
  [0. 0.]]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 0.]]
[array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
[[1. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[0, 1, 1]
0.0


[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [17]:
import numpy as np
# state_v = [0, 1/np.sqrt(3), 1/np.sqrt(3), 0, 1/np.sqrt(3), 0, 0, 0]
# state_v = tensor_list([[[1], [0]]]*N)
# state_v = tensor_list([[[1], [0]], [[1], [0]], [[0], [1]]])
N = 3
state_v = [0,0,1,0,1,0,0,1]
f = np.reshape(state_v, (2, 2**(N-1)))
gamma1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
# reshape V1
V1 = np.reshape(V1, (2**2, 2**(N-2)))
# V1[[1, 2]] = V1[[2, 1]]
print(V1)
# V1 = np.reshape(V1, (2, 2, 2**(N-2)))
gamma2, lambda2, V2 = np.linalg.svd(V1, full_matrices=False)
print(gamma2, lambda2, V2)
gamma2 = np.reshape(gamma2, (2, 2, 2))
lambda2 = lambda2 / np.linalg.norm(lambda2)
gamma3, lambda3, V3 = np.linalg.svd(V2, full_matrices=False)

print(gamma1)
print(lambda1)
print("22")
print(gamma2)
print(lambda2)
print(gamma3)

lambda1 = np.diag(lambda1)
lambda2 = np.diag(lambda2)
lambda3 = np.diag(lambda3)

mps = [[gamma1, lambda1], [gamma2, lambda2], V2]

contract(mps, N)


[[0.70710678 0.        ]
 [0.         1.        ]
 [0.         0.70710678]
 [0.         0.        ]]
[[ 0.          1.        ]
 [-0.81649658  0.        ]
 [-0.57735027  0.        ]
 [ 0.          0.        ]] [1.22474487 0.70710678] [[-0. -1.]
 [ 1.  0.]]
[[0. 1.]
 [1. 0.]]
[1.41421356 1.        ]
22
[[[ 0.          1.        ]
  [-0.81649658  0.        ]]

 [[-0.57735027  0.        ]
  [ 0.          0.        ]]]
[0.8660254 0.5      ]
[[ 0. -1.]
 [-1.  0.]]
[0, 1, 1]
0.0


[0.0,
 0.7071067811865475,
 0.0,
 0.0,
 0.7071067811865476,
 0.0,
 0.0,
 0.7071067811865475]

In [3]:

# state_v = [0, 1/np.sqrt(3), 1/np.sqrt(3), 0, 1/np.sqrt(3), 0, 0, 0]
# state_v = tensor_list([[[1], [0]]]*N)
# state_v = tensor_list([[[1], [0]], [[1], [0]], [[0], [1]]])
import numpy as np
N = 2
state_v = [1/2,1/2,1/2,0]
f = np.reshape(state_v, (2, 2**(N-1)))
gamma1, lambda1, V1 = np.linalg.svd(f, full_matrices=False)
# reshape V1
# V1 = np.reshape(V1, (2**2, 2**(N-2)))
# print(V1)
gamma2, lambda2, V2 = np.linalg.svd(np.abs(V1), full_matrices=False)

print(gamma1)
print(lambda1)
print(gamma2)

lambda1 = np.diag(np.abs(lambda1))

mps = [[gamma1, lambda1], gamma2]

contract(mps, N)

[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
[0.80901699 0.30901699]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


NameError: name 'contract' is not defined